### PR TITLE
Ensure broken packages stop hard on `mason_config` error

### LINKED ISSUE #370: MASON_SYSROOT: unbound variable
Ticket to track some unexpected fallout from #356 due to latent bugs.

It looks like there is an always undefined `MASON_SYSROOT` variable used [here](https://github.com/mapbox/mason/blob/master/mason.sh#L577-L584) in the default `mason_cflags` added in https://github.com/mapbox/mason/commit/944a64b37148ee7a0405cdf85be45bdc1e6e9af3

This is now silently leading to the `mason.ini` to be not fully built out because the command quietly fails on travis: `/Users/travis/build/mapbox/mason/mason.sh: line 577: MASON_SYSROOT: unbound variable`

So, there are two bugs perhaps:

  - Need to get rid of the unbound variable
  - Need to ensure that `pkg_config` failures stop the build rather than continuing

### PR DESCRIPTION
**Pull request by springmeyer**
This changes `mason` such that if `mason_config` fails, we will stop abruptly with an error and will avoid potentially publishing packages with a busted `mason.ini`.

It also:

 - Fixes #370 to ensure that `mason.ini` can be correctly generated even when `MASON_SYSROOT` is not passed (to avoid a regression from #356)
 - Fixes a few packages to not error due to invalid usage uncovered by #356

### CODE REVIEW

File: mason.sh [hunk 1]
```diff
@@ -505,7 +505,8 @@ function mason_config {
 function mason_write_config {
     local INI_FILE
     INI_FILE="${MASON_PREFIX}/mason.ini"
-    echo "`mason_config`" > "${INI_FILE}"
+    MASON_INI_DATA=$(set -e;mason_config)
+    echo "${MASON_INI_DATA}" > "${INI_FILE}"
```
Comment (kkaefer) [inline mason.sh]: Any reason they're now split up into two lines?

File: mason.sh [hunk 2]
```diff
@@ -564,24 +565,32 @@ function mason_try_binary {
...
-    for pkgconfig_file in ${MASON_PKGCONFIG_FILE}; do
+    for pkgconfig_file in ${MASON_PKGCONFIG_FILE:-}; do
         MASON_PKGCONFIG_FILES="${MASON_PKGCONFIG_FILES} ${MASON_PREFIX}/${pkgconfig_file}"
     done
     echo pkg-config ${MASON_PKGCONFIG_FILES}
 }
 
 function mason_cflags {
+    if [[ ! ${MASON_PKGCONFIG_FILE:-} ]]; then
+        mason_error " The MASON_PKGCONFIG_FILE variable not found in script.sh. Please either provide this variable or override both mason_cflags"
```
Comment (kkaefer) [inline mason.sh]: message seems to end abruptly

File: mason.sh (hunk 1 above)
Comment (springmeyer) [inline mason.sh]: If line 508 fails, now the `set- e` will prevent any blank mason.ini from being saved. In local testing it seemed this way needed.

File: mason.sh (hunk 2 above)
Comment (springmeyer) [inline mason.sh]: Fixed in 493b3b3

**Comment by springmeyer** [comment]
Merging this: the known outcome is that some older packages will fail to rebuild. This is desirable to avoid those packages ever being rebuilt (or new packages created as copies) with broken `mason.ini`. /cc @brunoabinader @tmpsantos @flippmoke @jfirebaugh
